package com.shortner.agent.orchestration.service;
import com.shortner.agent.orchestration.entity.*; import com.shortner.agent.orchestration.model.*; import com.shortner.agent.orchestration.repository.*;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class OrchestrationService {
 private static final int MAX_ATTEMPTS=3; private final WorkflowRunRepository runs; private final StageExecutionRepository stages; private final AuditEventRepository events;
 public OrchestrationService(WorkflowRunRepository runs,StageExecutionRepository stages,AuditEventRepository events){this.runs=runs;this.stages=stages;this.events=events;}
 @Transactional public WorkflowRun start(String scenario,String requirement){WorkflowRun run=runs.save(new WorkflowRun(scenario,requirement));for(Stage stage:Stage.values())stages.save(new StageExecution(run,stage));audit(run,null,"run created; graph initialized");refresh(run);return run;}
 @Transactional public void approve(long id,Stage stage,String approver){WorkflowRun run=get(id);StageExecution s=get(id,stage);if(s.getStatus()!=RunStatus.WAITING_APPROVAL)throw new IllegalStateException("stage is not awaiting approval");s.setStatus(RunStatus.READY);s.decide("approved by "+approver);audit(run,stage,"human approval recorded: "+approver);refresh(run);}
 @Transactional public void execute(long id,Stage stage,boolean success,String evidence){WorkflowRun run=get(id);StageExecution s=get(id,stage);if(s.getStatus()!=RunStatus.READY)throw new IllegalStateException("entry gate is closed");s.attempt();s.setStatus(RunStatus.RUNNING);audit(run,stage,"agent execution started; evidence="+evidence);if(success){s.setStatus(RunStatus.SUCCEEDED);s.decide(evidence);audit(run,stage,"exit gate passed");}else if(s.getAttempts()<MAX_ATTEMPTS){s.setStatus(RunStatus.READY);audit(run,stage,"failed; bounded retry "+s.getAttempts()+"/"+MAX_ATTEMPTS);}else{s.setStatus(RunStatus.FAILED);run.stop("retry budget exhausted at "+stage);audit(run,stage,"safe-stop triggered");}refresh(run);}
 @Transactional public void replan(long id,String reason){WorkflowRun run=get(id);for(StageExecution s:stages.findByRunId(id))if(s.getStage()!=Stage.REQUIREMENTS&&s.getStatus()!=RunStatus.PENDING){s.setStatus(RunStatus.PENDING);s.decide("invalidated: "+reason);}audit(run,Stage.REQUIREMENTS,"upstream change; downstream artifacts invalidated: "+reason);refresh(run);}
 @Transactional public void rollback(long id,String reason){WorkflowRun run=get(id);run.status(RunStatus.ROLLED_BACK);run.finish();audit(run,null,"rollback: "+reason);}
 @Transactional(readOnly=true) public RunView view(long id){WorkflowRun r=get(id);return new RunView(r,stages.findByRunId(id),events.findByRunIdOrderByAtAsc(id));}
 @Transactional(readOnly=true) public Metrics metrics(){List<WorkflowRun> all=runs.findAll();long completed=all.stream().filter(r->r.getStatus()==RunStatus.SUCCEEDED).count();long rolled=all.stream().filter(r->r.getStatus()==RunStatus.ROLLED_BACK).count();long retries=stages.findAll().stream().mapToLong(s->Math.max(0,s.getAttempts()-1)).sum();double latency=all.stream().filter(r->r.getFinishedAt()!=null).mapToLong(r->Duration.between(r.getStartedAt(),r.getFinishedAt()).toMillis()).average().orElse(0);return new Metrics(all.size(),all.isEmpty()?0:(double)completed/all.size(),retries,rolled,latency);}
 private void refresh(WorkflowRun run){if(run.getStatus()==RunStatus.SAFE_STOPPED||run.getStatus()==RunStatus.ROLLED_BACK)return;List<StageExecution> all=stages.findByRunId(run.getId());for(StageExecution s:all)if(s.getStatus()==RunStatus.PENDING&&s.getStage().dependencies().stream().allMatch(d->all.stream().anyMatch(x->x.getStage()==d&&x.getStatus()==RunStatus.SUCCEEDED))){s.setStatus(s.getStage().requiresApproval()?RunStatus.WAITING_APPROVAL:RunStatus.READY);audit(run,s.getStage(),s.getStatus()==RunStatus.READY?"entry gate opened":"human approval gate opened");}boolean done=all.stream().allMatch(s->s.getStatus()==RunStatus.SUCCEEDED);run.status(done?RunStatus.SUCCEEDED:RunStatus.RUNNING);if(done)run.finish();}
 private WorkflowRun get(long id){return runs.findById(id).orElseThrow(()->new NoSuchElementException("workflow run not found"));}private StageExecution get(long id,Stage s){return stages.findByRunIdAndStage(id,s).orElseThrow(()->new NoSuchElementException("stage not found"));}private void audit(WorkflowRun r,Stage s,String event){events.save(new AuditEvent(r,s,event));}
 public record RunView(WorkflowRun run,List<StageExecution> stages,List<AuditEvent> audit){} public record Metrics(long runs,double successRate,long retryCount,long rollbackCount,double averageEndToEndLatencyMs){}
}
